import type { NextPage } from "next";
import { signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";
type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};
const size = 100
const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const { data, status } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center h-screen p-4">
        <div className="pt-6 text-2xl text-blue-500 flex flex-col justify-center items-center w-full">
          {data?.user?.email}
          {data?.user?.image&&<Image src={data?.user?.image} width={`${size}px`} height={`${size}px`}/>}
          <p>{data?.user?.image}</p>
        </div>
        <div className="text-center">
          <button
            className="btn btn-secondary"
            onClick={() => signOut({ callbackUrl: "/auth" })}
          >
            Logout
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
